version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb  # Ensure this matches the database used in the app
    ports:
      - "3306:3306"  # Change to "3307:3306" if 3306 is in use on the host
    volumes:
      - db:/var/lib/mysql

  app-devops:
    depends_on:
      - mysqldb
    image: imgmohamed/devops:latest
    network_mode: host
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url": "jdbc:mysql://192.168.50.4:3306/mydb?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "root",
          "spring.jpa.hibernate.ddl-auto": "update",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
          "server.servlet.context-path": "/devops_project",
          "server.port": "8082",
          "management.endpoint.prometheus.enabled": "true",
          "management.endpoints.web.exposure.include": "prometheus"
        }
    stdin_open: true
    tty: true

volumes:
  db:
