services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb  # Changed from root to mydb for clarity
    ports:
      - 3306:3306  # Change this to 3307:3306 if 3306 is already in use on your host machine
    volumes:
      - db:/var/lib/mysql

  app-Devops:
    depends_on:
      - mysqldb
    image: imgmohamed/devops:1.0
    # build: ./  # Uncomment if you are building the app locally
    restart: on-failure
    ports:
      - 8082:8082  # Use a different host port if 8082 is occupied

    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/mydb?createDatabaseIfNotExist=true",  # Use mydb to match the MYSQL_DATABASE
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db: